### ISSUE TITLE
Suck in "TypeError: ModuleMocker is not a constructor"

### ISSUE THREAD

**Issue by zhen639** [NikhilVerma/jest-environment-node-debug-fixed#4]
After install this module and run the following command:
```
node --inspect-brk ./node_modules/.bin/jest --runInBand --env jest-environment-node-debug js/__tests__/components/tokenPayTest.js
```

I got the error:

```
TypeError: ModuleMocker is not a constructor

      at new NodeDebugEnvironment (node_modules/jest-environment-node-debug/index.js:54:29)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

How can I pass with it?
Thanks man

**Comment by jure** [comment]
Looks like this commit broke it: https://github.com/facebook/jest/commit/fc96580a1ca0402113cd39e2e1ee97182386aca7

**Comment by rmurcek** [comment]
This works for me running Node 7, but breaks in the same way with node 8. Does anyone have a workaround?

Command:
node --inspect-brk ./node_modules/.bin/jest --runInBand --env jest-environment-node-debug

Dependencies:
Node v8.0.0
Jest 20.0.4
